spring:
  cloud:
    alicloud:
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
      access-key: LTAI5tJJDu3Y2T5tBY916yBu
      secret-key: kBQi2R0XLRN9ogANZTN2nt6vwDkYoO
      bucket: gulimall-xhj