spring:
  cloud:
    gateway:
      routes:
        - id: test_gateway
          uri: https://www.qq.com
          predicates:
          - Query=url,qq

        - id: test2_gateway
          uri: http://www.baidu.com
          predicates:
          - Query=url,baidu

        - id: product_gateway
          uri: lb://gulimall-product
          predicates:
          - Path=/api/product/**
          filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_gateway
          uri: lb://gulimall-member
          predicates:
          - Path=/api/member/**
          filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_gateway
          uri: lb://gulimall-coupon
          predicates:
          - Path=/api/coupon/**
          filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: order_gateway
          uri: lb://gulimall-order
          predicates:
          - Path=/api/order/**
          filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_gateway
          uri: lb://gulimall-ware
          predicates:
          - Path=/api/ware/**
          filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third-party
          uri: lb://gulimall-third-party
          predicates:
          - Path=/api/thirdparty/**
          filters:
          - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: renren_gateway
          uri: lb://renren-fast
          predicates:
          - Path=/api/**
          filters:
          - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: gulimall_host
          uri: lb://gulimall-product
          predicates:
          - Host=gulimall.com

        - id: gulimall_search_host
          uri: lb://gulimall-search
          predicates:
          - Host=*.gulimall.com
