mybatis-plus:
  mapper-locations: classpath*:mepper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-not-delete-value: 1
      logic-delete-value: 0
spring:
  datasource:
    username: zhangxinbao
    password: zhangxinbao123@.
    url: jdbc:mysql://127.0.0.1:3306/gulimall_pms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 10011
logging:
  level:
    com.atguigu.gulimall: error