mybatis-plus:
  mapper-locations: classpath*:mepper/**/*.xml
  global-config:
    db-config:
      id-type: auto
spring:
  datasource:
    username: xhj
    password: xhj123@.
    url: jdbc:mysql://127.0.0.1:3306/xhj_ums?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  application:
    name: xhj-member

server:
  port: 8000
