mybatis-plus:
  mapper-locations: classpath*:mepper/**/*.xml
  global-config:
    db-config:
      id-type: auto
spring:
  datasource:
    username: xhj
    password: xhj123@.
    url: jdbc:mysql://127.0.0.1:3306/xhj_oms?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: xhj-order
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 9000
feign:
  httpclient:
    connection-timeout: 20000
  client:
    config:
      default:
        connectTimeout: 10000 #单位毫秒
        readTimeout: 10000 #单位毫秒